name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - uses: paambaati/codeclimate-action@v2.7.4
    - run: |
         python -m pip install --upgrade pip
         pip install poetry
         pip install flake8
         pip install pytest
    - run: make build
    - run: make package-install
    - run: make lint
    - run: make test
      env:
        CC_TEST_REPORTER_ID: f872ba877effcc46b4787f76188a740d4ac783dd066f286896f8aad8be7abc91 
    - run: make test-coverage
