name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install Poetry
      run: - pip install poetry

    - name: poetry init
      run: poetry init
      
    - name: Run pytest
      run: make test
