name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - run: |
         python -m pip install --upgrade pip
         pip install poetry
         pip install flake8
         pip install pytest
    - run: make build
    - run: make package-install
    - run: make lint
    - run: make test
    - run: poetry run pytest-cov
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: poetry run pytest --cov-report xml
