name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - uses: paambaati/codeclimate-action@v2.7.4
    - run: |
         python -m pip install --upgrade pip
         pip install poetry
         pip install flake8
         pip install pytest
    - run: make build
    - run: make package-install
    - run: make lint
    - run: make test
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: 945dfb58a832d233a3caeb84e3e6d3be212e8c7abcb48117fce63b9adcb43647
      with:
        coverageCommand: make test-coverage
