name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v3
    - run: pip install poetry
    - run: poetry add flake8
    - run: poetry add pytest
    - run: poetry run flake8 package/
