name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - run: |
         python -m pip install --upgrade pip
         pip install poetry
         pip install flake8
         pip install pytest
    - run:  make lint
