name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - run: |
        pip install flake8
        pip install poetry
        make install
    - run: python3 poetry run flake8 package/
